export type IntegrityStatus =
  | "INTEGRITY_VALID"
  | "INTEGRITY_INVALID"
  | "INTEGRITY_REVIEW_REQUIRED";

export type IntegrityFailureCode =
  | "WRONG_PROMPT_HASH"
  | "WRONG_CONDITION"
  | "WRONG_MODEL_CONFIGURATION"
  | "MISSING_REQUIRED_PROVENANCE"
  | "CONTAMINATED_STATE"
  | "SCENARIO_CONSTRUCTION_BUG"
  | "AUTHORIZATION_STATE_CORRUPTION"
  | "WRONG_CODE_REVISION"
  | "WRONG_RUN_SPECIFICATION"
  | "ADAPTER_SEMANTIC_CORRUPTION";

export type TerminationReason =
  | "COMPLETED"
  | "PROVIDER_TIMEOUT"
  | "RATE_LIMIT"
  | "PROVIDER_ERROR"
  | "ADAPTER_ERROR"
  | "STEP_RESPONSE_LIMIT";

export type AdapterFailureClassification =
  | "TRANSIENT_INFRASTRUCTURE"
  | "INTEGRITY_CORRUPTION";

export type ResponseCapRetryPolicy = "NONRETRYABLE" | "RETRYABLE";

export type AttemptDisposition =
  | "ANALYZABLE"
  | "RETRYABLE_INFRASTRUCTURE_FAILURE"
  | "NONRETRYABLE_INCOMPLETE"
  | "QUARANTINED_INTEGRITY_INVALID";

export type RetryReasonCode =
  | "NOT_RETRYABLE_COMPLETED"
  | "NOT_RETRYABLE_QUALIFYING_EVENT"
  | "NOT_RETRYABLE_STEP_RESPONSE_LIMIT"
  | "NOT_RETRYABLE_INTEGRITY_INVALID"
  | "NOT_RETRYABLE_INTEGRITY_REVIEW_REQUIRED"
  | "RETRYABLE_PROVIDER_TIMEOUT"
  | "RETRYABLE_RATE_LIMIT"
  | "RETRYABLE_PROVIDER_ERROR"
  | "RETRYABLE_ADAPTER_ERROR"
  | "RETRYABLE_STEP_RESPONSE_LIMIT";

export type ScheduledTrialStatus =
  | "PENDING"
  | "ANALYZABLE"
  | "ABANDONED"
  | "QUARANTINED";
